### PR TITLE
Add ENS reverse record

### PR DESCRIPTION
**Pull request by makoto**
Screenshot 2021-04-17 at 15 58 40

**DO NOT JUST MERGE**

You somehow need a way to set infra URL `REACT_APP_RPC_PROVIDER_URL=INFURA_URL`.  If this is not feasible, it has to hardcode that URL in the code itself.

## Note

The change will lazily look up the ENS name and shows once found. It works fine for a relatively small number but may take a long time to display or not display ENS names at all for +1000 events (The Berlin page probably takes 30 sec to 1 min to load ENS names). At least the change is unobtrusive so the initial load time should be the same.

There are a few outstanding items.

- Currently it lookup ENS names in the batch of 50 names at a time, but the change will wait until all names are returned. It could change so that it shows ENS names for every 50 names.
- Some name lookup calls are throwing exceptions (which I suppressed). There may be some bugs to fix.

### CODE REVIEW

**Comment by JamesCarnley** [comment]
This is a wonderful change, thank you! It does work pretty well too.

I'm wary of adding a dependency on Infura when we use The Graph for all of the data already. I looked into whether we could use [the ENS subgraph](https://thegraph.com/explorer/subgraph/ensdomains/ens) for name resolution and it seems like it may be possible. There's [this issue](https://github.com/ensdomains/ens-subgraph/issues/25) asking for reverse records to be added to the ENS subgraph but [Snapshot seems to be using The Graph to lookup ENS names for addresses](https://github.com/snapshot-labs/snapshot/commit/c1f0c6aef4b884b9de4d169ce6af70b6f34bd100). If we can make a call to the ENS subgraph instead of Infura it might simplify things and decrease long term maintenance.

I hope to mess around with this some more in the coming week but interested to hear everyone's thoughts.

**Comment by ragonzal** [comment]
Awesome, thanks for the PR @makoto!

@JamesCarnley I will merge this branch as-is so that we can show ENS as soon as possible. I've also tested it locally and it works fine.
Your points on Infura / TheGraph dependencies are valid, but I would wait until the Reverse Name is included on the ENS Graph (the issue you linked). I'm not completely on board with the Snapshot approach: they seem to query the contract, the subgraph and then merge response. The subgraph query is fetching the names the account registered, it's not actually the reverse name of an address.

I'll leave an issue on the repo to replace the dependency if ENS subgraphs adds the reverse name

**Comment by JamesCarnley** [comment]
@ragonzal This doesn't work unless an Infura account is setup and REACT_APP_RPC_PROVIDER_URL is populated in .env in production. Who can do that?

**Comment by ragonzal** [comment]
@JamesCarnley I do, and did :)
Sorry I didn't mention it before. I see it working on prod!
Thank you both!

**Pull request merged**
